### PR TITLE
Vulkan: make it an error to create surface without GLFW_NO_API

### LINKED ISSUE #1194: Make it an error to create a glfwCreateWindowSurface without GLFW_NO_API
Long story short: I spent 3 days debugging a crash in the NVIDIA driver on `vkQueuePresentKHR` because I forgot to add `glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);`.

Using Vulkan and OpenGL / OpenGL ES on the same window isn't defined AFAIK. Would it make sense to produce an error if `glfwCreateWindowSurface` is called on a window that doesn't have the `GLFW_CLIENT_API` hint set to `GLFW_NO_API`? I'm sure this would help preserve some other developer's sanity.

### PR DESCRIPTION
**Pull request by Kangz**
OpenGL / OpenGL ES cannot share presentation on a window with Vulkan.
This adds an error to `glfwCreateWindowSurface` when it is called on a
window without the GLFW_CLIENT_API hint set to GLFW_NO_API. This
prevents undefined bahevior and hard to debug crashes.

Fixes #1194.

### CODE REVIEW

**Comment by Kangz** [comment]
First time contributing to GLFW, please let me know if I missed anything or there are improvements needed.

File: src/vulkan.c [hunk 1]
```diff
@@ -317,6 +317,14 @@ GLFWAPI VkResult glfwCreateWindowSurface(VkInstance instance,
         return VK_ERROR_EXTENSION_NOT_PRESENT;
     }
 
+    if (window->context.client != GLFW_NO_API)
+    {
+        _glfwInputError(GLFW_API_UNAVAILABLE,
```
[the remark this answers is not in the document]
Comment (elmindreda) [reply src/vulkan.c]: Of the existing ones, `INVALID_VALUE` might be the closest.

File: README.md [hunk 2]
```diff
@@ -178,6 +178,8 @@ information on what to include when reporting a bug.
 - Added `GLFW_OSMESA_CONTEXT_API` for creating OpenGL contexts with
   [OSMesa](https://www.mesa3d.org/osmesa.html) (#281)
 - Added `GenerateMappings.cmake` script for updating gamepad mappings
+- Added a `glfwCreateWindowSurface` error when `GLFW_CLIENT_API` isn't
+  `GLFW_NO_API` (#1194)
```
Comment (elmindreda) [inline README.md]: This is a `Made` or `Changed`:
```
- Made `glfwCreateWindowSurface` emit an error when the window has a context (#1194,#1205)
```

File: README.md [hunk 3]
```diff
@@ -452,6 +454,7 @@ skills.
  - Santi Zupancic
  - Jonas Ådahl
  - Lasse Öörni
+ - Corentin Wallez
```
Comment (elmindreda) [inline README.md]: Names are sorted by surname.

File: docs/vulkan.dox [hunk 4]
```diff
@@ -205,7 +205,7 @@ an existing Vulkan surface.
 @section vulkan_window Creating the window
 
 Unless you will be using OpenGL or OpenGL ES with the same window as Vulkan,
-there is no need to create a context.  You can disable context creation with the
```
Comment (elmindreda) [inline docs/vulkan.dox]: This seems to be a stray edit.

File: include/GLFW/glfw3.h [hunk 5]
```diff
@@ -5441,6 +5441,11 @@ GLFWAPI int glfwGetPhysicalDevicePresentationSupport(VkInstance instance, VkPhys
  *  glfwGetRequiredInstanceExtensions to check what instance extensions are
  *  required.
  *
+ *  The window surface cannot be shared with another API so the window must
+ *  have been created with the [client api hint](@ref GLFW_CLIENT_API_attrib)
+ *  set to `GLFW_NO_API` otherwise it generates a @ref GLFW_API_UNAVAILABLE
+ *  error and returns `VK_ERROR_NATIVE_WINDOW_IN_USE_KHR`.
+ *
```
Comment (elmindreda) [inline include/GLFW/glfw3.h]: This and the one above are great.

File: docs/vulkan.dox (hunk 4 above)
Comment (elmindreda) [reply docs/vulkan.dox]: Yes please. Two spaces are used in all GLFW comments and documentation sources.

**Comment by elmindreda** [comment]
I can do the final janitor stuff in you're in a hurry.

File: README.md (hunk 2 above)
Comment (Kangz) [reply README.md]: Done

File: README.md (hunk 3 above)
Comment (Kangz) [reply README.md]: Done

File: include/GLFW/glfw3.h (hunk 5 above)
Comment (Kangz) [reply include/GLFW/glfw3.h]: Thanks!

File: docs/vulkan.dox (hunk 4 above)
Comment (Kangz) [reply docs/vulkan.dox]: Done

**Comment by Kangz** [comment]
There's no hurry, I was just afk for a while :) Addressed all comments, let me know if there are more changes needed!

File: src/vulkan.c [hunk 6]
```diff
@@ -317,6 +317,14 @@ GLFWAPI VkResult glfwCreateWindowSurface(VkInstance instance,
         return VK_ERROR_EXTENSION_NOT_PRESENT;
     }
 
+    if (window->context.client != GLFW_NO_API)
+    {
+        _glfwInputError(GLFW_INVALID_VALUE,
+                        "Vulkan: Window surface creation requires the window "
+                        "to have the client API set to GLFW_NO_API");
```
Comment (elmindreda) [inline src/vulkan.c]: Error string literals should be kept whole even past 80 to help people who grep for them.

File: include/GLFW/glfw3.h [hunk 7]
```diff
@@ -5441,6 +5441,11 @@ GLFWAPI int glfwGetPhysicalDevicePresentationSupport(VkInstance instance, VkPhys
  *  glfwGetRequiredInstanceExtensions to check what instance extensions are
  *  required.
  *
+ *  The window surface cannot be shared with another API so the window must
+ *  have been created with the [client api hint](@ref GLFW_CLIENT_API_attrib)
+ *  set to `GLFW_NO_API` otherwise it generates a @ref GLFW_INVALID_VALUE error
+ *  and returns `VK_ERROR_NATIVE_WINDOW_IN_USE_KHR`.
+ *
```
Comment (elmindreda) [inline include/GLFW/glfw3.h]: The new error must also be listed under `@errors` below.

**Comment by elmindreda** [comment]
That was fast, thank you! Just two more then and I'll merge.

File: src/vulkan.c (hunk 6 above)
Comment (Kangz) [reply src/vulkan.c]: Done

File: include/GLFW/glfw3.h (hunk 7 above)
Comment (Kangz) [reply include/GLFW/glfw3.h]: Done

**Comment by elmindreda** [comment]
Thank you!
